---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: apache
  name: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      volumes:
      - name: web-root
        persistentVolumeClaim:
          claimName: apache-nfs-pvc
      containers:
      - image: lovelearnlinux/webserver:v1
        name: apache
        volumeMounts:
        - name: web-root # template.spec.volumes[].name
          mountPath: /var/www/html # mount inside of container
          #readOnly: true # if enforcing read-only on volume
        ports:
        - containerPort: 80