apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingres
  namespace: default  # Replace with your actual namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: demo-nginx.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service  # Must match the service name with the targeted service
                port:
                  number: 8080