apiVersion: v1
kind: Service 
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: proxy
      port: 8080
      targetPort: 80
    - name: application
      port: 8081
      targetPort: 8082
      #NodePort: 32505 #we can define the node port or it define it own
  

#kubectl port-forward service/nginx-service 8080:8080