apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: nginx-deployment
  annotations:  #this annotation for describing the update casue 
    kubernetes.io/change-cause: "reduce the replicaset"
spec: 
  replicas: 3
  selector: 
   matchLabels:
     app: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec: 
      containers:
        - name: nginx-container
          image: nginx:alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
#kubectl get all
#Check the revision of deployment
#kubectl rollout history deployment/nginx-deployment
#kubectl rollout undo deployment/nginx-deployment --to-revision=2