apiVersion: v1
kind: Service 
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - port: 8080
      targetPort: 80
  type: NodePort

#kubectl port-forward service/nginx-service 8080:8080