apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1awsebs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0beb39f3d32ee9cfe
    fsType: ext4