apiVersion: v1 #we can find the version this way "kubectl api-resources | grep pod"
kind: Pod
metadata: #information of the object like (Resource Name, labels and other)
  name: my-nginx-pod1
  namespace: default
  labels: # this label we have to use to identify or filter the pod 
    team: integrations
    app: todo
spec: # we can define the specification of the resources 
  containers:
    - name: nginx-container
      image: mysql:latest
      ports:
        - containerPort: 80

---
#to check the pod status run the following command 
#kubectl api-resources | grep pod
#kubectl describe pods my-nginx-pod1 -n test-ns
#kubectl get pod my-nginx-pod1 -n test-ns
#kubectl logs -n test-ns my-nginx-pod1 
#kubectl exec -it -n test-ns my-nginx-pod1 -- bash
#kubectl exec -it -n test-ns my-nginx-pod1 -c <ContainerName> -- bash
#kubectl port-forward -n test-ns my-nginx-pod1 8080:80