apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod2
  namespace: default
  labels:
    app: myapp
spec:
  containers:
  - name: mynignx-container1
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
