apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage #define the container volume label that will reffer to the volume claim 
      mountPath: /data #define the data mount point in the container. 
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
